[project]
name = "auth-firebase"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
  "nitric ==1.2.3", 
  "betterproto ==2.0.0b6", 
  "firebase-admin >=6.6.0"
]

[tool.uv]
dev-dependencies = [
    "watchdog>=5.0.3",
]
